Initial trip checks changes #2151
nwfsc-fram/TripsApi pull request #136
Opened 2021-02-04 02:15 UTC by Mak-NOAA

Initial changes for issue #2151:  https://github.com/nwfsc-fram/boatnet/issues/2151

2021-02-04 17:25 UTC, melinashak-noaa requested changes
Thanks for working on this Mak and getting everything setup. Just a few comments.

2021-02-04 18:00 UTC, sethgerou-noaa approved these changes
see comments on dropping errors docs

2021-02-04 18:16 UTC, melinashak-noaa commented on routes/index.ts
> +        masterDev.destroy(previousTripError.doc._id, previousTripError.doc._rev);
Got it, that makes sense, yes I like the idea of an errors array in the trips doc. Although would it get too large that maybe we need to store it in it's own doc? Well yes storing it in the trip doc should be good.

2021-02-04 18:29 UTC, sethgerou-noaa commented on routes/index.ts
> +        masterDev.destroy(previousTripError.doc._id, previousTripError.doc._rev);
was thinking a separate errors doc with array of errors so as not to clutter the trip doc.

2021-02-04 18:46 UTC, melinashak-noaa commented on routes/index.ts
> +        masterDev.destroy(previousTripError.doc._id, previousTripError.doc._rev);
sure that works

2021-02-05 06:44 UTC, Mak-NOAA commented on routes/index.ts
> +        masterDev.destroy(previousTripError.doc._id, previousTripError.doc._rev);
@sethgerou-noaa I've setup some time for us to set up the trip errors as an array in trip record tomorrow

2021-02-05 06:45 UTC, Mak-NOAA commented on routes/index.ts
> +const runTripChecks = async (req, res) => {
@melinashak-noaa yeah we just quickly made that up....I like runTripErrorChecks

2021-02-05 17:57 UTC, melinashak-noaa approved these changes

2021-02-05 20:29 UTC, Mak-NOAA commented on routes/index.ts
> +        masterDev.destroy(previousTripError.doc._id, previousTripError.doc._rev);
We created a trip error array within the trip error document.

2021-02-05 20:30 UTC, merged